The Next Web home page clone  merge request
temesghentekeste/thenextweb-clone pull request #4
Opened 2020-04-24 16:43 UTC by 8Bts

We created a branch called "homepage" and collaborated on that branch.

- [ ] On the initial commit, we created a basic structure for the page using semantics.

- [ ] "Mobile first" approach is used in order to achieve responsiveness principles.

- [ ] Page's content sections are made one by one for _mobile_, _tablet_, and _desktop_ versions separately. 

- [ ] Elements are positioned using Grid, FlexBox, and Float

2020-04-25 08:03 UTC, sumancrest0001 commented
**Changes required**
**Extraordinary work @temesghentekeste :clap :clap**

Your layout looks very much similar to that of the original and it is responsive at defined breakpoints.
I couldn't have asked more than this but there is two minor issues that need to be addressed to make it perfect. I know they are very minor and I am sure that it won't take much time.

[Required] It seems that you forget to add title on the third article of the main section.
Currently :point_down: :point_down: 
![Screenshot from 2020-04-25 13-40-55](https://user-images.githubusercontent.com/37747619/80274595-4160d600-86fb-11ea-8ace-97a4a42a6605.png)

It should have a  title (like APP INSIGHT) before the heading :point_down: 
![Screenshot from 2020-04-25 13-40-28](https://user-images.githubusercontent.com/37747619/80274608-63f2ef00-86fb-11ea-85de-e717314d1bc4.png)

2020-04-25 08:10 UTC, sumancrest0001 commented
[Required] Let's remove some bottom margins from the articles, especially first and last. It will help us to align the last line of the article at the bottom as in the original site.
Currently :point_down: 
![Screenshot from 2020-04-25 13-51-31](https://user-images.githubusercontent.com/37747619/80274738-525e1700-86fc-11ea-81a7-219ccdd9fd96.png)

It should be like this :point_down: 
![Screenshot from 2020-04-25 13-51-03](https://user-images.githubusercontent.com/37747619/80274745-5e49d900-86fc-11ea-98f3-a33614b43f7e.png)

2020-04-25 08:13 UTC, sumancrest0001 commented
[Required] We have to fix the images sizes of the latest news section on a small screen. Currently, image size is different for each article which disturbed the alignment of titles also. 
on your project :point_down: 
![Screenshot from 2020-04-25 13-51-48](https://user-images.githubusercontent.com/37747619/80274817-cb5d6e80-86fc-11ea-892c-51c35f9427fc.png)

On the original site :point_down: 
![Screenshot from 2020-04-25 13-52-04](https://user-images.githubusercontent.com/37747619/80274822-d912f400-86fc-11ea-8fc1-94514ec6ba72.png)

2020-04-25 08:19 UTC, sumancrest0001 commented on css/style.css
> +
[Optional] Even though other CSS stylings are perfect. Can we just remove the repetition of styling between these two classes? Let's follow the DRY principle. [pathright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) (reference) [reference](https://speckyboy.com/good-bad-css-practicesl)

2020-04-25 08:22 UTC, sumancrest0001 requested changes
**Kindly make the above-requested changes and request for another review.**

**Happy coding !!**
Have any questions? Contact me on slack **Suman Shrestha**

2020-04-25 08:28 UTC, temesghentekeste commented
Thanks, @sumancrest0001 we will follow your review and make the necessary amendments.

2020-04-27 10:04 UTC, lekegitrepo commented
#### Hi @8Bts and @temesghentekeste :clap: :+1: :100: 
#### Good job :muscle:  for implementing the required changes mentioned in the previous review.
#### This project is approved :1st_place_medal: 

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

2020-04-27 10:05 UTC, lekegitrepo approved these changes
#### Status: Approved.

2020-04-27 10:16 UTC, merged

2020-04-27 10:56 UTC, temesghentekeste commented
Thanks, @lekegitrepo for approving the project.